### ISSUE TITLE
Access Key matching the implicit accounts gets updated on each transfer

### ISSUE THREAD

**Issue by achernik** [near/near-indexer-for-explorer#304]
Access Key matching the implicit accounts gets updated on each transfer, setting `last_update_block_height` to the block height of the transfer execution and `deleted_by_receipt_id` to null. 

Steps to reproduce: 
 1) Create an Implicit Account with a transfer
 2) Add another Full access key to that account
 3) Delete initial access key (the one matching the implicit account name)
 4) Make another transfer to the account

Result: 
 The initial access key in the DB looks like it hasn't been deleted, even though it has been.

**Comment by frol** [comment]
Yeah, we worked under a bit different assumptions back in the days. We should not act like blockchain re-creates the access key with every transfer, yet we need to ensure that we create it with the first transfer (including the cases when the account is re-created after being deleted)

@achernik Thanks for raising it 👍 

@pkudinov I believe this is a good onboarding issue for Monday

**Comment by frol** [comment]
Here is an account on testnet that exhibits this behaviour: https://explorer.testnet.near.org/accounts/cfb46d6579ca320a3dd78c7a3133b4a20bb6724302c413e792db7130bd740205

**Comment by frol** [comment]
While the fix is implemented in #317, we will need to re-index the whole history of testnet and mainnet. To do so, I suggested disabling all the other tables, creating a new temporary table `access_keys_reindexed` alongside the existing tables, and re-indexing the whole history there, once all the data is there we can swap the tables and drop the old one.

cc @morgsmccauley @khorolets
