### ISSUE TITLE
feat: Store account changes

### ISSUE THREAD

**Issue by khorolets** [near/near-indexer-for-explorer#9]
`StreamerMessage` also returns `state_changes` that also should be stored in database

**Comment by frol** [comment]
# Motivation

State changes include [all sorts of changes](https://github.com/near/nearcore/blob/f1e116bb3952bfe07f4aaa3298e5564170b99156/core/primitives/src/views.rs#L1290-L1330), but we only care about the balance changes now since some of the balance changes are not related to the transactions or receipts (e.g. validator rewards), and the only way we observe those is through the state changes. Explorer needs to provide a better understanding on why the balance has ever changed, and Wallet has this need as well.

# Implementation

Facts:

* The [account update state changes](https://github.com/near/nearcore/blob/f1e116bb3952bfe07f4aaa3298e5564170b99156/core/primitives/src/views.rs#L1293-L1297) contain the dump of the account state as is (it is not a diff change).
* The state changes can be [caused by various triggers](https://github.com/near/nearcore/blob/f1e116bb3952bfe07f4aaa3298e5564170b99156/core/primitives/src/views.rs#L1250-L1262):
  * `NotWritableToDisk` -- this state should be unreachable (it means that we may as well just crash the indexer if we ever observe it)
  * `InitialState` -- those are changes from genesis, and we cannot query those via view client, so if you observe them, act similar to `NotWritableToDisk`
  * `TransactionProcessing { tx_hash: CryptoHash }` -- we just record that the balance at that particular transaction was X amount and Y staked
  * `ActionReceiptProcessingStarted { receipt_hash: CryptoHash }`, `ActionReceiptGasReward { receipt_hash: CryptoHash }`, `ReceiptProcessing { receipt_hash: CryptoHash }`, `PostponedReceipt { receipt_hash: CryptoHash }` -- same as for `TransactionProcessing`, but reference receipt id instead of transaction hash (it is my bad that those are named as `receipt_hash` here, sorry, those are `receipt_id`s)
  * `UpdatedDelayedReceipts`, `ValidatorAccountsUpdate` -- these are state changes related to the chunk/block, so we can attribute them to the block/chunk hash; `ValidatorAccountsUpdate` is where we observe the validator rewards, unlocking the unstaked balance, validation node kick-out, and slashing [in the future] on the epoch boundary

That said, I suggest we do the following `account_balances` table (for the lack of a better name):

* `account_id`
* `block_timestamp`
* `block_hash`
* `chunk_hash`
* `transaction_hash` (NULLable since validator rewards will only be attributed to the block)
* `receipt_id` (NULLable since validator rewards and transaction processing is not related to any receipt)
* `update_cause`: [`BLOCK_PROCESSING`, `TRANSACTION_PROCESSING`, `RECEIPT_PROCESSING`] (we can easily deduce this cause based on the NULL status on the `receipt_id` and `transaction_hash`, so I am not 100% sold on adding this field, but I think it is still useful to better express the intent)
* `nonstaked_balance` (that is `account.locked` on AccountView)
* `staked_balance` (that is `account.staked` on AccountView)
* `storage_usage` (measured in bytes; I am not 100% sure we need this field, and I am not 100% sure the naming is good)

**Comment by khorolets** [comment]
Closed by #57
